MODINV-1333: MappingMetadataCacheTest: IllegalStateException: Client is closed
https://folio-org.atlassian.net/browse/MODINV-1333

Due to incorrect Vertx setup there can be a race condition in MappingMetadataCacheTest resulting in the failures:

```
[ERROR]   MappingMetadataCacheTest.shouldReturnEmptyOptionalWhenGetNotFoundByRecordType:149 » IllegalState
[ERROR]   MappingMetadataCacheTest.shouldReturnEmptyOptionalWhenGetNotFoundOnSnapshotLoading:137 » IllegalState
[ERROR]   MappingMetadataCacheTest.shouldReturnMappingMetadata:71 » IllegalState Client ...
[ERROR]   MappingMetadataCacheTest.shouldReturnMappingMetadataByRecordType:85 » IllegalState
```

Example: https://jenkins-aws.indexdata.com/job/folio-org/job/mod-inventory/job/MODINV-1332-release-21.0.18-plus/1/execution/node/42/log/

Cause:

```
java.lang.IllegalStateException: Client is closed
	at io.vertx.core.http.impl.HttpClientImpl.checkClosed(HttpClientImpl.java:405)
```

Fix:

Move Vertx setup into @BeforeClass